apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-replica
  namespace: my-namespace
  labels:
    app: nginx-app
    tier: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      tier: frontend
  template:
    metadata:
      labels:
        tier: frontend
    spec:
      containers:
      - name: nginx-container
        image: nginx
